-- =========================================================
-- 1. USERS
-- =========================================================
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       email VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,

                       phone_number VARCHAR(50) UNIQUE,
                       full_name VARCHAR(255) NOT NULL,
                       avatar_url TEXT,

                       status VARCHAR(50) NOT NULL,

                       last_login TIMESTAMP WITH TIME ZONE,

                       reset_password_token VARCHAR(255),
                       reset_password_token_expiry TIMESTAMP WITH TIME ZONE,

                       created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 2. ROLES
-- =========================================================
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       name VARCHAR(100) NOT NULL UNIQUE,
                       description VARCHAR(255)
);


-- =========================================================
-- 3. PERMISSIONS
-- =========================================================
CREATE TABLE permissions (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             name VARCHAR(150) NOT NULL UNIQUE,
                             description VARCHAR(255)
);


-- =========================================================
-- 4. USER ROLES
-- =========================================================
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,

                            PRIMARY KEY (user_id, role_id),

                            CONSTRAINT fk_user_roles_user
                                FOREIGN KEY (user_id)
                                    REFERENCES users(id)
                                    ON DELETE CASCADE,

                            CONSTRAINT fk_user_roles_role
                                FOREIGN KEY (role_id)
                                    REFERENCES roles(id)
                                    ON DELETE CASCADE
);


-- =========================================================
-- 5. ROLE PERMISSIONS
-- =========================================================
CREATE TABLE role_permissions (
                                  role_id BIGINT NOT NULL,
                                  permission_id BIGINT NOT NULL,

                                  PRIMARY KEY (role_id, permission_id),

                                  CONSTRAINT fk_role_permissions_role
                                      FOREIGN KEY (role_id)
                                          REFERENCES roles(id)
                                          ON DELETE CASCADE,

                                  CONSTRAINT fk_role_permissions_permission
                                      FOREIGN KEY (permission_id)
                                          REFERENCES permissions(id)
                                          ON DELETE CASCADE
);


-- =========================================================
-- 6. REFRESH TOKENS
-- =========================================================
CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                user_id BIGINT NOT NULL,

                                token_hash VARCHAR(64) NOT NULL UNIQUE,

                                expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                revoked_at TIMESTAMP WITH TIME ZONE,

                                replaced_by_token_id BIGINT,

                                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                created_by_ip VARCHAR(45),
                                user_agent VARCHAR(512),

                                CONSTRAINT fk_refresh_tokens_user
                                    FOREIGN KEY (user_id)
                                        REFERENCES users(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_refresh_tokens_replaced_by
                                    FOREIGN KEY (replaced_by_token_id)
                                        REFERENCES refresh_tokens(id)
);

CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_tokens(user_id);

CREATE INDEX idx_refresh_tokens_expires_at
    ON refresh_tokens(expires_at);


-- =========================================================
-- 7. DEFAULT ROLES
-- =========================================================
INSERT INTO roles (name, description) VALUES
                                          ('CUSTOMER', 'Khach hang dat san cau long'),
                                          ('STAFF', 'Nhan vien van hanh san cau long'),
                                          ('OWNER', 'Chu san cau long');


-- =========================================================
-- 8. PERMISSIONS
-- Đã bỏ time-slot vì hệ thống không dùng bảng time_slots
-- =========================================================
INSERT INTO permissions (name, description) VALUES

                                                ('court:read', 'Xem danh sach san'),
                                                ('court:write', 'Them sua xoa san'),

                                                ('booking:read', 'Xem lich dat san'),
                                                ('booking:create', 'Tao don dat san'),
                                                ('booking:update', 'Cap nhat don dat san'),
                                                ('booking:cancel', 'Huy don dat san'),

                                                ('payment:read', 'Xem thanh toan'),
                                                ('payment:write', 'Tao hoac cap nhat thanh toan'),

                                                ('customer:read', 'Xem thong tin khach hang'),

                                                ('staff:manage', 'Quan li nhan vien'),

                                                ('venue:read', 'Xem co so san cau long'),
                                                ('venue:write', 'Them sua xoa co so'),

                                                ('equipment:read', 'Xem san pham va thiet bi'),
                                                ('equipment:write', 'Quan li san pham va thiet bi'),

                                                ('order:read', 'Xem don hang'),
                                                ('order:create', 'Tao don hang'),
                                                ('order:update', 'Cap nhat don hang'),

                                                ('review:read', 'Xem danh gia'),
                                                ('review:create', 'Tao danh gia'),
                                                ('review:manage', 'Quan li danh gia'),

                                                ('report:read', 'Xem bao cao doanh thu va hoat dong');


-- =========================================================
-- 9. CUSTOMER PERMISSIONS
-- =========================================================
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         JOIN permissions p ON p.name IN (
                                          'court:read',
                                          'venue:read',
                                          'booking:create',
                                          'booking:cancel',
                                          'payment:read',
                                          'equipment:read',
                                          'order:create',
                                          'review:read',
                                          'review:create'
    )
WHERE r.name = 'CUSTOMER';


-- =========================================================
-- 10. STAFF PERMISSIONS
-- =========================================================
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         JOIN permissions p ON p.name IN (
                                          'court:read',
                                          'venue:read',
                                          'booking:read',
                                          'booking:create',
                                          'booking:update',
                                          'booking:cancel',
                                          'payment:read',
                                          'payment:write',
                                          'customer:read',
                                          'equipment:read',
                                          'order:read',
                                          'order:create',
                                          'order:update',
                                          'review:read'
    )
WHERE r.name = 'STAFF';


-- =========================================================
-- 11. OWNER PERMISSIONS
-- Owner có toàn bộ permissions
-- =========================================================
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         CROSS JOIN permissions p
WHERE r.name = 'OWNER';


-- =========================================================
-- 12. STAFF PROFILES
-- =========================================================
CREATE TABLE staff_profiles (
                                user_id BIGINT PRIMARY KEY,

                                employee_code VARCHAR(50) NOT NULL UNIQUE,

    -- CCCD/CMND
                                identity_card VARCHAR(20) UNIQUE,

                                hire_date DATE,

    -- Ví dụ: CASHIER, RECEPTIONIST, MANAGER
                                position VARCHAR(100),

                                salary NUMERIC(12,2),

                                notes TEXT,

                                CONSTRAINT fk_staff_profile_user
                                    FOREIGN KEY (user_id)
                                        REFERENCES users(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT chk_staff_salary
                                    CHECK (
                                        salary IS NULL
                                            OR salary >= 0
                                        )
);


-- =========================================================
-- 13. VENUES
-- Một hệ thống có thể có nhiều cơ sở
-- =========================================================
CREATE TABLE venues (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        name VARCHAR(255) NOT NULL,

                        address TEXT NOT NULL,

                        phone_number VARCHAR(50),

    -- Tọa độ dùng cho bản đồ / tìm sân gần nhất
                        latitude NUMERIC(10,7),
                        longitude NUMERIC(10,7),

                        opening_time TIME,
                        closing_time TIME,

    -- ACTIVE / INACTIVE
                        status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',

                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT chk_venue_operating_hours
                            CHECK (
                                opening_time IS NULL
                                    OR closing_time IS NULL
                                    OR closing_time > opening_time
                                )
);


-- =========================================================
-- 14. COURTS
-- =========================================================
CREATE TABLE courts (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        venue_id BIGINT NOT NULL,

    -- Code chỉ cần unique trong từng venue
                        court_code VARCHAR(50) NOT NULL,

                        name VARCHAR(150) NOT NULL,

                        description TEXT,

                        price_per_hour NUMERIC(12,2) NOT NULL,

    -- AVAILABLE / MAINTENANCE / INACTIVE
                        status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE',

                        image_url TEXT,

                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT fk_courts_venues
                            FOREIGN KEY (venue_id)
                                REFERENCES venues(id)
                                ON DELETE CASCADE,

                        CONSTRAINT uq_court_venue_code
                            UNIQUE (venue_id, court_code),

                        CONSTRAINT chk_court_price
                            CHECK (price_per_hour >= 0)
);


-- =========================================================
-- 15. BOOKINGS
-- Một booking có thể chứa nhiều sân
-- =========================================================
CREATE TABLE bookings (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          booking_code VARCHAR(50) NOT NULL UNIQUE,

    -- Có account thì lưu customer_id
                          customer_id BIGINT,

    -- Khách vãng lai thì lưu guest info
                          guest_name VARCHAR(255),
                          guest_phone VARCHAR(50),

                          booking_date DATE NOT NULL,

                          total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,

    -- PENDING / CONFIRMED / CANCELLED / COMPLETED / EXPIRED
                          status VARCHAR(50) NOT NULL DEFAULT 'PENDING',

                          note TEXT,

    -- Ai tạo booking
    -- Có thể là customer hoặc staff
                          created_by BIGINT,

                          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_booking_customer
                              FOREIGN KEY (customer_id)
                                  REFERENCES users(id),

                          CONSTRAINT fk_booking_created_by
                              FOREIGN KEY (created_by)
                                  REFERENCES users(id),

                          CONSTRAINT chk_booking_total_amount
                              CHECK (total_amount >= 0),

    -- Booking phải thuộc user hoặc khách vãng lai
                          CONSTRAINT chk_booking_customer_identity
                              CHECK (
                                  customer_id IS NOT NULL
                                      OR (
                                      guest_name IS NOT NULL
                                          AND guest_phone IS NOT NULL
                                      )
                                  )
);


CREATE INDEX idx_bookings_customer
    ON bookings(customer_id);

CREATE INDEX idx_bookings_date
    ON bookings(booking_date);

CREATE INDEX idx_bookings_status
    ON bookings(status);


-- =========================================================
-- 16. BOOKING DETAILS
-- Mỗi dòng là một sân trong booking
-- =========================================================
CREATE TABLE booking_details (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                 booking_id BIGINT NOT NULL,

                                 court_id BIGINT NOT NULL,

                                 start_time TIME NOT NULL,
                                 end_time TIME NOT NULL,

    -- Giá tại thời điểm đặt
                                 unit_price NUMERIC(12,2) NOT NULL,

                                 subtotal NUMERIC(12,2) NOT NULL,

    -- ACTIVE / CANCELLED / COMPLETED
                                 status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',

                                 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT fk_booking_detail_booking
                                     FOREIGN KEY (booking_id)
                                         REFERENCES bookings(id)
                                         ON DELETE CASCADE,

                                 CONSTRAINT fk_booking_detail_court
                                     FOREIGN KEY (court_id)
                                         REFERENCES courts(id),

                                 CONSTRAINT chk_booking_detail_time
                                     CHECK (end_time > start_time),

                                 CONSTRAINT chk_booking_detail_price
                                     CHECK (
                                         unit_price >= 0
                                             AND subtotal >= 0
                                         )
);


CREATE INDEX idx_booking_details_booking
    ON booking_details(booking_id);

CREATE INDEX idx_booking_details_court
    ON booking_details(court_id);


-- =========================================================
-- 17. PAYMENTS
-- Một booking có thể thanh toán nhiều lần
-- =========================================================
CREATE TABLE payments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          booking_id BIGINT NOT NULL,

                          amount NUMERIC(12,2) NOT NULL,

    -- CASH / BANK_TRANSFER / MOMO / VNPAY ...
                          payment_method VARCHAR(50) NOT NULL,

    -- PENDING / PAID / FAILED / REFUNDED
                          payment_status VARCHAR(50) NOT NULL,

                          transaction_code VARCHAR(255),

                          paid_at TIMESTAMP WITH TIME ZONE,

                          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_payment_booking
                              FOREIGN KEY (booking_id)
                                  REFERENCES bookings(id),

                          CONSTRAINT chk_payment_amount
                              CHECK (amount > 0)
);


-- =========================================================
-- 18. PAYMENT ALLOCATIONS
-- Dùng để chia payment theo từng booking detail
-- Hỗ trợ tách bill
-- =========================================================
CREATE TABLE payment_allocations (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     payment_id BIGINT NOT NULL,

                                     booking_detail_id BIGINT NOT NULL,

                                     amount NUMERIC(12,2) NOT NULL,

                                     CONSTRAINT fk_payment_allocation_payment
                                         FOREIGN KEY (payment_id)
                                             REFERENCES payments(id)
                                             ON DELETE CASCADE,

                                     CONSTRAINT fk_payment_allocation_booking_detail
                                         FOREIGN KEY (booking_detail_id)
                                             REFERENCES booking_details(id)
                                             ON DELETE CASCADE,

                                     CONSTRAINT chk_payment_allocation_amount
                                         CHECK (amount > 0)
);


-- =========================================================
-- 19. REVIEWS
-- Review theo từng sân trong booking detail
-- =========================================================
CREATE TABLE reviews (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Mỗi detail chỉ review một lần
                         booking_detail_id BIGINT NOT NULL UNIQUE,

                         customer_id BIGINT NOT NULL,

                         rating INT NOT NULL,

                         comment TEXT,

                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT fk_review_booking_detail
                             FOREIGN KEY (booking_detail_id)
                                 REFERENCES booking_details(id),

                         CONSTRAINT fk_review_customer
                             FOREIGN KEY (customer_id)
                                 REFERENCES users(id),

                         CONSTRAINT chk_rating
                             CHECK (rating BETWEEN 1 AND 5)
);


-- =========================================================
-- 20. EQUIPMENT / PRODUCTS
-- Hỗ trợ vừa bán vừa cho thuê
-- =========================================================
CREATE TABLE equipment (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           name VARCHAR(255) NOT NULL,

                           quantity INT NOT NULL DEFAULT 0,

    -- Giá bán
                           sale_price NUMERIC(12,2),

    -- Giá thuê
                           rental_price NUMERIC(12,2),

    -- Có bán hay không
                           is_for_sale BOOLEAN NOT NULL DEFAULT FALSE,

    -- Có cho thuê hay không
                           is_for_rent BOOLEAN NOT NULL DEFAULT FALSE,

    -- AVAILABLE / OUT_OF_STOCK / INACTIVE
                           status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE',

                           created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT chk_equipment_quantity
                               CHECK (quantity >= 0),

                           CONSTRAINT chk_equipment_prices
                               CHECK (
                                   (sale_price IS NULL OR sale_price >= 0)
                                       AND
                                   (rental_price IS NULL OR rental_price >= 0)
                                   )
);


-- =========================================================
-- 21. BOOKING EQUIPMENT
-- Thiết bị thuê kèm từng booking detail
-- =========================================================
CREATE TABLE booking_equipment (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   booking_detail_id BIGINT NOT NULL,

                                   equipment_id BIGINT NOT NULL,

                                   quantity INT NOT NULL,

                                   unit_price NUMERIC(12,2) NOT NULL,

                                   subtotal NUMERIC(12,2) NOT NULL,

                                   CONSTRAINT fk_booking_equipment_detail
                                       FOREIGN KEY (booking_detail_id)
                                           REFERENCES booking_details(id)
                                           ON DELETE CASCADE,

                                   CONSTRAINT fk_booking_equipment_equipment
                                       FOREIGN KEY (equipment_id)
                                           REFERENCES equipment(id),

                                   CONSTRAINT chk_booking_equipment_quantity
                                       CHECK (quantity > 0),

                                   CONSTRAINT chk_booking_equipment_price
                                       CHECK (
                                           unit_price >= 0
                                               AND subtotal >= 0
                                           )
);


-- =========================================================
-- 22. NOTIFICATIONS
-- =========================================================
CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               user_id BIGINT NOT NULL,

                               title VARCHAR(255) NOT NULL,

                               message TEXT NOT NULL,

    -- BOOKING / PAYMENT / SYSTEM / PROMOTION ...
                               notification_type VARCHAR(50),

                               is_read BOOLEAN NOT NULL DEFAULT FALSE,

                               created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_notification_user
                                   FOREIGN KEY (user_id)
                                       REFERENCES users(id)
                                       ON DELETE CASCADE
);


-- =========================================================
-- 23. ORDERS
-- Cho phép mua đồ mà không cần đặt sân
-- =========================================================
CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        order_code VARCHAR(50) NOT NULL UNIQUE,

                        customer_id BIGINT,

    -- Khách vãng lai
                        guest_name VARCHAR(255),
                        guest_phone VARCHAR(50),

                        total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,

    -- PENDING / CONFIRMED / COMPLETED / CANCELLED
                        status VARCHAR(50) NOT NULL DEFAULT 'PENDING',

                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT fk_order_customer
                            FOREIGN KEY (customer_id)
                                REFERENCES users(id),

                        CONSTRAINT chk_order_amount
                            CHECK (total_amount >= 0),

                        CONSTRAINT chk_order_customer_identity
                            CHECK (
                                customer_id IS NOT NULL
                                    OR (
                                    guest_name IS NOT NULL
                                        AND guest_phone IS NOT NULL
                                    )
                                )
);


-- =========================================================
-- 24. ORDER ITEMS
-- =========================================================
CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             order_id BIGINT NOT NULL,

                             equipment_id BIGINT NOT NULL,

                             quantity INT NOT NULL,

    -- Giá bán tại thời điểm mua
                             unit_price NUMERIC(12,2) NOT NULL,

                             subtotal NUMERIC(12,2) NOT NULL,

                             CONSTRAINT fk_order_item_order
                                 FOREIGN KEY (order_id)
                                     REFERENCES orders(id)
                                     ON DELETE CASCADE,

                             CONSTRAINT fk_order_item_equipment
                                 FOREIGN KEY (equipment_id)
                                     REFERENCES equipment(id),

                             CONSTRAINT chk_order_item_quantity
                                 CHECK (quantity > 0),

                             CONSTRAINT chk_order_item_price
                                 CHECK (
                                     unit_price >= 0
                                         AND subtotal >= 0
                                     )
);

INSERT INTO venues (name, address, phone_number, latitude, longitude, opening_time, closing_time, status)
VALUES
    (
        'Sài Gòn Central Badminton',
        '123 Nguyễn Thị Minh Khai, Phường Bến Thành, Quận 1, TP.HCM',
        '0901234567',
        10.776889,
        106.695312,
        '05:00:00',
        '23:00:00',
        'ACTIVE'
    ),
    (
        'Tân Bình Sport Club',
        '456 Lý Thường Kiệt, Phường 7, Quận Tân Bình, TP.HCM',
        '0908765432',
        10.789123,
        106.654321,
        '06:00:00',
        '22:30:00',
        'ACTIVE'
    ),
    (
        'Thủ Đức Arena Badminton',
        '789 Võ Văn Ngân, Phường Linh Chiểu, TP. Thủ Đức, TP.HCM',
        '0911223344',
        10.850123,
        106.758901,
        '05:30:00',
        '22:00:00',
        'ACTIVE'
    );