-- 1. STAFF_PROFILES
-- Bỏ quản lý lương
ALTER TABLE staff_profiles
DROP COLUMN salary;

-- Nếu muốn cố định nhân viên hiện tại là thu ngân
ALTER TABLE staff_profiles
    ALTER COLUMN position SET DEFAULT 'CASHIER';

CREATE TABLE cashier_shifts (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                staff_id BIGINT NOT NULL,

                                venue_id BIGINT NOT NULL,

                                opened_at TIMESTAMP WITH TIME ZONE
                                                NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                opening_cash NUMERIC(12,2) NOT NULL,

                                closed_at TIMESTAMP WITH TIME ZONE,

                                expected_closing_cash NUMERIC(12,2),

                                actual_closing_cash NUMERIC(12,2),

                                cash_difference NUMERIC(12,2),

    -- OPEN / CLOSED
                                status VARCHAR(20) NOT NULL DEFAULT 'OPEN',

                                notes TEXT,

                                created_at TIMESTAMP WITH TIME ZONE
                                    NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_cashier_shift_staff
                                    FOREIGN KEY (staff_id)
                                        REFERENCES users(id),

                                CONSTRAINT fk_cashier_shift_venue
                                    FOREIGN KEY (venue_id)
                                        REFERENCES venues(id),

                                CONSTRAINT chk_shift_opening_cash
                                    CHECK (opening_cash >= 0),

                                CONSTRAINT chk_shift_expected_cash
                                    CHECK (
                                        expected_closing_cash IS NULL
                                            OR expected_closing_cash >= 0
                                        ),

                                CONSTRAINT chk_shift_actual_cash
                                    CHECK (
                                        actual_closing_cash IS NULL
                                            OR actual_closing_cash >= 0
                                        ),

                                CONSTRAINT chk_shift_closed_time
                                    CHECK (
                                        closed_at IS NULL
                                            OR closed_at >= opened_at
                                        )
);

CREATE TABLE cash_movements (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                cashier_shift_id BIGINT NOT NULL,

    -- CASH_IN / CASH_OUT
                                movement_type VARCHAR(20) NOT NULL,

    -- BOOKING_PAYMENT
    -- ORDER_PAYMENT
    -- REFUND
    -- CASH_ADJUSTMENT
    -- OTHER
                                source_type VARCHAR(50) NOT NULL,

                                amount NUMERIC(12,2) NOT NULL,

    -- ID của booking/payment/order liên quan nếu có
                                reference_id BIGINT,

                                description TEXT,

                                created_by BIGINT NOT NULL,

                                created_at TIMESTAMP WITH TIME ZONE
                                    NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_cash_movement_shift
                                    FOREIGN KEY (cashier_shift_id)
                                        REFERENCES cashier_shifts(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_cash_movement_created_by
                                    FOREIGN KEY (created_by)
                                        REFERENCES users(id),

                                CONSTRAINT chk_cash_movement_amount
                                    CHECK (amount > 0),

                                CONSTRAINT chk_cash_movement_type
                                    CHECK (
                                        movement_type IN ('CASH_IN', 'CASH_OUT')
                                        )
);

ALTER TABLE payments
    ADD COLUMN cashier_shift_id BIGINT,
ADD COLUMN received_by BIGINT;

ALTER TABLE payments
    ADD CONSTRAINT fk_payment_cashier_shift
        FOREIGN KEY (cashier_shift_id)
            REFERENCES cashier_shifts(id);

ALTER TABLE payments
    ADD CONSTRAINT fk_payment_received_by
        FOREIGN KEY (received_by)
            REFERENCES users(id);

CREATE UNIQUE INDEX uq_staff_open_shift
    ON cashier_shifts(staff_id)
    WHERE status = 'OPEN';

ALTER TABLE bookings
    ADD COLUMN venue_id BIGINT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM booking_details bd
        JOIN courts c ON c.id = bd.court_id
        GROUP BY bd.booking_id
        HAVING COUNT(DISTINCT c.venue_id) > 1
    ) THEN
        RAISE EXCEPTION 'Khong the gan venue: booking hien tai co san thuoc nhieu co so';
    END IF;
END
$$;

UPDATE bookings b
SET venue_id = source.venue_id
FROM (
    SELECT bd.booking_id, MIN(c.venue_id) AS venue_id
    FROM booking_details bd
    JOIN courts c ON c.id = bd.court_id
    GROUP BY bd.booking_id
) source
WHERE source.booking_id = b.id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM bookings WHERE venue_id IS NULL) THEN
        RAISE EXCEPTION 'Khong the xac dinh venue cho booking khong co booking detail';
    END IF;
END
$$;

ALTER TABLE bookings
    ALTER COLUMN venue_id SET NOT NULL;

ALTER TABLE bookings
    ADD CONSTRAINT fk_booking_venue
        FOREIGN KEY (venue_id)
            REFERENCES venues(id);

CREATE INDEX idx_bookings_venue
    ON bookings(venue_id);

CREATE OR REPLACE FUNCTION enforce_booking_detail_venue()
RETURNS TRIGGER AS $$
DECLARE
    booking_venue_id BIGINT;
    court_venue_id BIGINT;
BEGIN
    SELECT venue_id INTO booking_venue_id
    FROM bookings
    WHERE id = NEW.booking_id;

    SELECT venue_id INTO court_venue_id
    FROM courts
    WHERE id = NEW.court_id;

    IF booking_venue_id IS DISTINCT FROM court_venue_id THEN
        RAISE EXCEPTION 'Court % khong thuoc venue cua booking %', NEW.court_id, NEW.booking_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_booking_detail_same_venue
    BEFORE INSERT OR UPDATE OF booking_id, court_id
    ON booking_details
    FOR EACH ROW
    EXECUTE FUNCTION enforce_booking_detail_venue();

CREATE OR REPLACE FUNCTION enforce_booking_venue_update()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.venue_id IS DISTINCT FROM OLD.venue_id
        AND EXISTS (
            SELECT 1
            FROM booking_details bd
            JOIN courts c ON c.id = bd.court_id
            WHERE bd.booking_id = NEW.id
              AND c.venue_id <> NEW.venue_id
        ) THEN
        RAISE EXCEPTION 'Tat ca san trong booking % phai thuoc venue %', NEW.id, NEW.venue_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_booking_same_venue_on_update
    BEFORE UPDATE OF venue_id
    ON bookings
    FOR EACH ROW
    EXECUTE FUNCTION enforce_booking_venue_update();
